const data = {
  products: [
    {
      _id: "1",
      name: "The Witcher - O Último Desejo",
      category: "Livro",
      image: "/images/p1.jpg",
      price: 120,
      brand: "WMF Fontes",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "The Witcher - A Espada do Destino",
      category: "Livro",
      image: "/images/p2.jpg",
      price: 120,
      brand: "WMF Fontes",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "The Witcher - O Sangue dos Elfos",
      category: "Livro",
      image: "/images/p3.jpg",
      price: 120,
      brand: "WMF Fontes",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "The Witcher - Tempo do Desprezo",
      category: "Livro",
      image: "/images/p4.jpg",
      price: 120,
      brand: "WMF Fontes",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "The Witcher - Batismo de Fogo",
      category: "Livro",
      image: "/images/p5.jpg",
      price: 120,
      brand: "WMF Fontes",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "The Witcher - ",
      category: "Livro",
      image: "/images/p6.jpg",
      price: 120,
      brand: "WMF Fontes",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "The Witcher - A Senhora do Lago",
      category: "Livro",
      image: "/images/p7.jpg",
      price: 120,
      brand: "WMF Fontes",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;